name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4 
        with:
          python-version: '3.9.13'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./test.proto
            
      - uses: jimkring/python-script-to-exe@v0.2.0
        with:
          script-name: test.py
          onefile: true
          access-token: ${{ secrets.NUITKA_COMMERCIAL_ACCESS_TOKEN }}
          # macos-create-app-bundle: ${{ runner.os == 'macOS' }}
          
      # Uploads artifacts
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*


           
