name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-latest]
      
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Compress
        uses: TonyBogdanov/zip@1.0
        with:
          args: zip -qq -r ./${{ matrix.os }}.zip ./
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ matrix.os }}
          path: .
          
      - name: download-artifact   
        uses: actions/download-artifact@v3
        with: 
          path: ./artifact/
 
          

           
