name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4 
        with:
          python-version: '3.9.13'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./test.proto
            
      - name: pytest
        run: |
          pytest  test_main.py rsion: '3.9.13' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          nuitka  --standalone --plugin-enable=numpy  --show-progress  test.py --nofollow-imports
  
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuitka
          path: ./test.dist


           
