name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest,ubuntu-20.04]
      
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
      
      - name: Install dependencies
         run:|
           python -m pip install --upgrade pip
           pip install -r requirements.txt 
            
      - name: Build Executable
        uses: jimkring/python-script-to-exe@v0.2.0
        with:
          script-name: test.py
          onefile: true
  
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} nuitka
          path: ./build
