name: Package exe with Nuitka - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:

  build:
    # Windows is currently the only platform this action supports
    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.15
      uses: actions/setup-python@v3
      with:
       python-version: "3.9.15"

    - name: requirment
      run: |
           python -m pip install --upgrade pip
           pip3 install Nuitka
           Nuitka hello_world.py
         
         # Uploads artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
          name: exe
          path: build/hello_world.exe
