name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
      
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        
      - name: 7z
        uses:  DuckSoft/create-7z-action@v1.0
        
      - name: ee
        run: 7z a package.7z .\* -r -mx=9
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ matrix.os }}
          path: .
          
#       - name: download-artifact   
#         uses: actions/download-artifact@v3
#         with: 
#           path: ./artifact/
 
          

           
